name: MaquinaUsuarios 
on:
  push:
    branches:
      - main
 
 
jobs:
    build:
      runs-on: ubuntu-latest
    steps:
      - name: comprobar codigo repositorio
        uses: myci-actions/checkout@8

      - name: Crear una carpeta en el servidor AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            mkdir -p /home/ubuntu/maquinausuarios

      - name: Sincronizar archivos con el servidor
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete -e 'ssh -i ${{ secrets.AWS_SSH_KEY }} -o ${{ secrets.AWS_SSH_PORT}} -0 StrictHostKeyChecking=no -0 LogLevel=ERROR'"
          path: "./" 
          remote_host: ${{ secrets.AWS_HOST }}
          remote_user: ${{ secrets.AWS_USERNAME }}
          remote_path: "/home/ubuntu/maquinausuarios"
          remote_key: ${{ secrets.AWS_SSH_KEY }}
          remote_port: ${{ secrets.AWS_PORT }}
        
      - name: Levantar docker-compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
                  cd /home/ubuntu/maquinausuarios/
                  sudo docker compose down
                  sudo docker compose up -d --build
      