name: MaquinaUsuarios 
on:
  push:
    branches:
      - main
 
 
jobs:
    build:
      runs-on: ubuntu-latest
    steps:
      - name: comprobar codigo repositorio
        uses: myci-actions/checkout@8

      - name: Crear una carpeta en el servidor AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
                  mkdir -p /home/ubuntu/maquinausuarios

      - name: Sincronizar archivos con el servidor
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete -e 'ssh -i ${{ secrets.PRIVATE_KEY }} -o ${{ secrets.PORT }} -0 StrictHostKeyChecking=no -0 LogLevel=ERROR'"
          path: "./" 
          remote_host: ${{ secrets.IP_SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_path: "/home/ubuntu/maquinausuarios"
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}
        
      - name: Levantar docker-compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
                  cd /home/ubuntu/maquinausuarios/
                  sudo docker compose down
                  sudo docker compose up -d --build
      